motd=A Minecraft Server
sub-motd=Powered by Nukkit
server-port=19132
server-ip=0.0.0.0
view-distance=10
achievements=on
announce-player-achievements=on
spawn-protection=16
gamemode=0
force-gamemode=off
difficulty=0
hardcore=off
pvp=on
white-list=on
generator-settings=
level-name=world
level-seed=
level-type=default
enable-rcon=off
rcon.password=1MjBlNzQxZ
force-resources=off
force-resources-allow-client-packs=off
xbox-auth=on
auto-save=on
force-language=off
enable-query=off
allow-flight=off
allow-nether=on
allow-the-end=on
max-players=50
drop-spawners=on
spawn-animals=on
spawn-mobs=on
whitelist-reason=§cServer is white-listed
rcon.port=25575
level-auto-compaction=on
level-auto-compaction-ticks=36000
encryption=on
bed-spawnpoints=on
explosion-break-blocks=on
stop-in-game=off
op-in-game=on
space-name-mode=ignore
xp-bottles-on-creative=on
spawn-eggs=on
mob-ai=on
entity-auto-spawn-task=on
entity-despawn-task=on
language=eng
shutdown-message=§cServer closed
save-player-data=on
query-plugins=off
debug-level=1
async-workers=auto
zlib-provider=2
compression-level=5
compression-threshold=256
use-snappy-compression=off
rak-packet-limit=120
enable-rak-send-cookie=on
timeout-milliseconds=25000
auto-tick-rate=on
auto-tick-rate-limit=20
base-tick-rate=1
always-tick-players=off
light-updates=off
clear-chunk-tick-list=on
spawn-threshold=56
chunk-sending-per-tick=4
chunk-ticking-per-tick=40
chunk-ticking-radius=3
chunk-generation-queue-size=8
chunk-generation-population-queue-size=8
ticks-per-autosave=6000
ticks-per-entity-spawns=200
ticks-per-entity-despawns=12000
thread-watchdog=on
thread-watchdog-tick=60000
nether=on
end=on
vanilla-portals=on
portal-ticks=80
multi-nether-worlds=
anti-xray-worlds=
do-not-tick-worlds=
worlds-entity-spawning-disabled=
load-all-worlds=on
ansi-title=off
block-listener=on
multiversion-min-protocol=0
multiversion-max-protocol=-1
vanilla-bossbars=off
strong-ip-bans=off
worlds-level-auto-save-disabled=
temp-ip-ban-failed-xbox-auth=off
call-data-pk-send-event=on
call-batch-pk-send-event=on
do-level-gc=on
skin-change-cooldown=15
check-op-movement=off
do-not-limit-interactions=off
do-not-limit-skin-geometry=on
automatic-bug-report=on
anvils-enabled=on
save-player-data-by-uuid=on
persona-skins=on
call-entity-motion-event=on
update-notifications=on
bstats-metrics=on
cache-chunks=off
async-chunks=on
deprecated-verbose=on
server-authoritative-movement=server-auth
server-authoritative-block-breaking=on
use-client-spectator=on
enable-experiment-mode=on
use-waterdog=off
enable-spark=off
hastebin-token=
leveldb-cache-mb=64
use-native-leveldb=off
enable-raw-ores=on
enable-new-paintings=on
enable-new-chicken-eggs-laying=on
forced-safety-enchant=on
enable-vibrant-visuals=on
enable-raytracing=on
netease-client-support=off
only-allow-netease-client=off
